# Generated by Django 6.0.3 on 2026-09-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
        ('profissional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Cirurgia')),
                ('local', models.CharField(max_length=150, verbose_name='Local da Cirurgia')),
                ('procedimento', models.CharField(max_length=200, verbose_name='Procedimento')),
                ('cuidados_pos_operatorios', models.TextField(blank=True, default='', verbose_name='Cuidados Pós-Operatórios')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirurgias', to='pet.pet', verbose_name='Pet')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias', to='profissional.profissional', verbose_name='Profissional Responsável')),
            ],
            options={
                'verbose_name': 'Cirurgia',
                'verbose_name_plural': 'Cirurgias',
            },
        ),
    ]
