# Generated by Django 6.1.1 on 2026-09-30 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Exame')),
                ('data_realizacao', models.DateField(verbose_name='Data de Realização')),
                ('resultado', models.TextField(blank=True, default='', verbose_name='Resultado')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='consulta.consulta', verbose_name='Consulta de Origem')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='pet.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
            },
        ),
    ]
