# Generated by Django 6.0.3 on 2026-08-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome'),
        ),
    ]
