# Generated by Django 6.1 on 2026-08-24 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tutor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                ("especie", models.CharField(max_length=50, verbose_name="Espécie")),
                ("raca", models.CharField(max_length=50, verbose_name="Raça")),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Macho"), ("F", "Fêmea")],
                        max_length=1,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="tutor.tutor",
                        verbose_name="Tutor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
            },
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        max_length=100, verbose_name="Nome do Medicamento"
                    ),
                ),
                ("dosagem", models.CharField(max_length=50, verbose_name="Dosagem")),
                (
                    "frequencia",
                    models.CharField(max_length=50, verbose_name="Frequência"),
                ),
                ("data_inicio", models.DateField(verbose_name="Data de Início")),
                ("data_fim", models.DateField(verbose_name="Data do Fim")),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicamentos",
                        to="pet.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medicamento",
                "verbose_name_plural": "Medicamentos",
            },
        ),
        migrations.CreateModel(
            name="Exame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Exame"),
                ),
                (
                    "data_realizacao",
                    models.DateField(verbose_name="Data de Realização"),
                ),
                (
                    "veterinario",
                    models.CharField(max_length=150, verbose_name="Veterinário"),
                ),
                (
                    "resultado",
                    models.TextField(blank=True, null=True, verbose_name="Resultado"),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exames",
                        to="pet.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exame",
                "verbose_name_plural": "Exames",
            },
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data da Consulta")),
                (
                    "profissional",
                    models.CharField(
                        max_length=150, verbose_name="Profissional Responsável"
                    ),
                ),
                ("diagnostico", models.TextField(verbose_name="Diagnóstico")),
                (
                    "observacoes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="pet.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Cirurgia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data da Cirurgia")),
                (
                    "profissional",
                    models.CharField(
                        max_length=150, verbose_name="Profissional Responsável"
                    ),
                ),
                (
                    "local",
                    models.CharField(max_length=150, verbose_name="Local da Cirurgia"),
                ),
                (
                    "procedimento",
                    models.CharField(max_length=200, verbose_name="Procedimento"),
                ),
                (
                    "cuidados_pos_operatorios",
                    models.TextField(verbose_name="Cuidados Pós-Operatórios"),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cirurgias",
                        to="pet.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cirurgia",
                "verbose_name_plural": "Cirurgias",
            },
        ),
        migrations.CreateModel(
            name="AvisoVacinacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_aviso", models.DateField(verbose_name="Data do Aviso")),
                ("status", models.CharField(max_length=50, verbose_name="Status")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos_vacina",
                        to="pet.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aviso de Vacinação",
                "verbose_name_plural": "Avisos de Vacinação",
            },
        ),
        migrations.CreateModel(
            name="Vacina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Vacina"),
                ),
                ("data_aplicacao", models.DateField(verbose_name="Data de Aplicação")),
                ("data_reforco", models.DateField(verbose_name="Data de Reforço")),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacinas",
                        to="pet.pet",
                        verbose_name="Pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacina",
                "verbose_name_plural": "Vacinas",
            },
        ),
    ]
