# Generated by Django 6.0.3 on 2026-08-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('especialidade', models.CharField(max_length=100, verbose_name='Especialidade')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
            },
        ),
        migrations.RemoveField(
            model_name='avisovacinacao',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='exame',
            name='veterinario',
        ),
        migrations.RemoveField(
            model_name='medicamento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='vacina',
            name='data_aplicacao',
        ),
        migrations.RemoveField(
            model_name='vacina',
            name='data_reforco',
        ),
        migrations.RemoveField(
            model_name='vacina',
            name='pet',
        ),
        migrations.AddField(
            model_name='exame',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exames', to='pet.consulta', verbose_name='Consulta de Origem'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='pet.consulta', verbose_name='Consulta de Prescrição'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='duracao_dias',
            field=models.PositiveIntegerField(default=1, verbose_name='Duração (Dias)'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='descricao',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='intervalo_doses_dias',
            field=models.PositiveIntegerField(default=0, verbose_name='Intervalo entre Doses (Dias)'),
        ),
        migrations.AddField(
            model_name='vacina',
            name='quantidade_dose',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de Doses'),
        ),
        migrations.AlterField(
            model_name='avisovacinacao',
            name='status',
            field=models.CharField(default='Pendente', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='cuidados_pos_operatorios',
            field=models.TextField(blank=True, default='', verbose_name='Cuidados Pós-Operatórios'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='observacoes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='exame',
            name='resultado',
            field=models.TextField(blank=True, default='', verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias', to='pet.profissional', verbose_name='Profissional Responsável'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to='pet.profissional', verbose_name='Profissional'),
        ),
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(verbose_name='Data de Aplicação')),
                ('proxima_dose', models.DateField(blank=True, null=True, verbose_name='Próxima Dose / Reforço')),
                ('dose_atual', models.PositiveIntegerField(default=1, verbose_name='Dose Atual')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='pet.pet', verbose_name='Pet')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='pet.vacina', verbose_name='Vacina')),
            ],
            options={
                'verbose_name': 'Vacinação',
                'verbose_name_plural': 'Vacinações',
            },
        ),
        migrations.AddField(
            model_name='avisovacinacao',
            name='vacinacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='pet.vacinacao', verbose_name='Vacinação'),
        ),
    ]
