# Generated by Django 6.0.3 on 2026-08-19 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Medicamento')),
                ('dosagem', models.CharField(max_length=50, verbose_name='Dosagem')),
                ('frequencia', models.CharField(max_length=50, verbose_name='Frequência')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('duracao_dias', models.IntegerField(verbose_name='Duração em Dias')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Exame')),
                ('data_realizacao', models.DateField(verbose_name='Data de Realização')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.consulta')),
            ],
        ),
    ]
