# Generated by Django 6.0.3 on 2026-09-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '__first__'),
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Medicamento')),
                ('dosagem', models.CharField(max_length=50, verbose_name='Dosagem')),
                ('frequencia', models.CharField(max_length=50, verbose_name='Frequência')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('duracao_dias', models.PositiveIntegerField(default=1, verbose_name='Duração (Dias)')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicamentos', to='consulta.consulta', verbose_name='Consulta de Prescrição')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='pet.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
            },
        ),
    ]
