# Generated by Django 6.0.3 on 2026-09-06 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet', '0001_initial'),
        ('vacina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateField(verbose_name='Data de Aplicação')),
                ('proxima_dose', models.DateField(blank=True, null=True, verbose_name='Próxima Dose / Reforço')),
                ('dose_atual', models.PositiveIntegerField(default=1, verbose_name='Dose Atual')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinacoes', to='pet.pet', verbose_name='Pet')),
                ('vacina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicacoes', to='vacina.vacina', verbose_name='Vacina')),
            ],
            options={
                'verbose_name': 'Vacinação',
                'verbose_name_plural': 'Vacinações',
            },
        ),
        migrations.CreateModel(
            name='AvisoVacinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aviso', models.DateField(verbose_name='Data do Aviso')),
                ('status', models.CharField(default='Pendente', max_length=50, verbose_name='Status')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('vacinacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='vacinacao.vacinacao', verbose_name='Vacinação')),
            ],
            options={
                'verbose_name': 'Aviso de Vacinação',
                'verbose_name_plural': 'Avisos de Vacinação',
            },
        ),
    ]
