# Generated by Django 6.0.3 on 2026-08-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Cirurgia')),
                ('profissional', models.CharField(max_length=150, verbose_name='Profissional Responsável')),
                ('local', models.CharField(max_length=150, verbose_name='Local da Cirurgia')),
                ('procedimento', models.CharField(max_length=200, verbose_name='Procedimento')),
                ('cuidados_pos_operatorios', models.TextField(verbose_name='Cuidados Pós-Operatórios')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Consulta')),
                ('profissional', models.CharField(max_length=150, verbose_name='Profissional Responsável')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Vacina')),
                ('data_aplicacao', models.DateField(verbose_name='Data de Aplicação')),
                ('data_reforco', models.DateField(verbose_name='Data de Reforço')),
            ],
        ),
    ]
