# Generated by Django 6.1 on 2026-08-24 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinica", "0002_medicamento_exame"),
        ("tutor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consulta",
            options={
                "ordering": ["-data"],
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
            },
        ),
        migrations.AddField(
            model_name="consulta",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultas",
                to="tutor.tutor",
            ),
        ),
    ]
