# Generated by Django 6.0.3 on 2026-08-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Vacina')),
                ('quantidade_dose', models.PositiveIntegerField(default=1, verbose_name='Quantidade de Doses')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('intervalo_doses_dias', models.PositiveIntegerField(default=0, verbose_name='Intervalo entre Doses (Dias)')),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
            },
        ),
    ]
